### ISSUE TITLE
hiring, in the parlance of our times, man....

### ISSUE THREAD

**Issue by Indyresjoel** [Indyresjoel/theindyreshole#1]
In light of some of the major decisions looming in our companies near future, we must consider the hiring questions. It seems inevitable, whether we are landing new projects, or jumping into a stand alone product that hiring is inevitable. Obviously, there are implications based on the relativity of how this is done, (hiring 2 people feels different than hiring 8.) but setting aside those anticipatory concerns, I've learned that there are concerns which precede them and they need to be ventilated. 

**1) Bad Habits Yo.**
It's come to my attention that some team members are concerned that even hiring one or two new developers could cause more stress than relief, even though we are in need of additional resources to handle to overwhelming weight of work we have on our plates. The cited reason for their concern is that, in order to handle the capacity and workload we currently are burdened with, the development team has made situational sacrifices in 'best practices' in certain occasions. While understandable, the concern is that if we add new members to the team, we would run the risk of starting new team members without taking the time to properly on board them, and essentially, letting our team's active use of sub par habits set a lower standard of code quality in cement. And, to finish the analogy, if we were to get buried, new team members and all, under the workload we are anticipating, we would likely not adjust the bad habits while the cement is still wet, the net result being, at this time next year, we'd have a team that is much larger, but with much lower quality standards. (If I did not do that justice, I'd recommend speaking up.)

Since hiring, and that quite soon, does seem to be an inevitability, I am sharing this in the hope that we make time to address these concerns. In my experience, by the time you hear one of these concerns, it's likely that there are many more concerns just like it. The tip of the iceberg principle. So, I suggest that people start speaking up (by adding comments to this issue) to Alex and myself with these concerns. We will then put them into a list, call a meeting to order with the dev team, and discuss and vote upon what our standards should be, and/or, what specific bad habits need to be addressed. The net result of these discussions will be adapted into our employee onboarding manual and training materials which will get pushed asap so that they could potentially be used on the next wave of hires. 

**2) Job Roles**
Much appreciated would be people's input on what job roles, skill sets, or missing pieces would be terrific to have filled here. Also, when we consider the role, I'd like to pick a tv or movie character who would be the ideal candidate for the job. 

ie: "I think we need someone who is really compassionate, honest, and funny. They should know how to flip hamburgers underwater, or at least have a little experience with it. They would be a great addition because our team would benefit from having someone who understands the basics of underwater burger flipping and would do a good job representing the burger consumer while doing the hardcore prep work. They'd ideally help with documenting and training for the client side as well, and would often play product owner role. If this role was filled by a fictional character, it would best be filled by Spongebob Squarepants." 

**3) Hiring Recommendations**
Additionally, I'd like to remind everyone that we have never posted a job recruitment before. While I'm open to doing it, as usual, I'd like to start with those we know and trust. If you know anyone whom you know that would love to work at Indy Res, regardless of obstacles (too expensive, has a good job, hates commuting... etc. forget that bullshit. Just dream a little.) please message me with their names and contact info. I intend to make this round of hiring very very intentional and we will be aiming to bring in exactly the right kind of person and skill set for the roles we are looking for. Thanks for your recommendations. When you submit a name, include how you know them and why you think they'd be a good addition to our team please. I don't need a list of people who simply are looking for work. Just submit solid people who'd compliment our technical needs and our culture.

That's it for hiring. Dev team, I'd like an acknowledgement of reading this from each of you, if you include your opinion, thoughts, etc, even better. If you want to share something, but do it in private, feel free.

**Comment by alexindrez** [comment]
@Indyresjoel ack

**Comment by Jim-IndRez** [comment]
I have read this @Indyresjoel

**Comment by Mel-IndyRes** [comment]
+1

**Comment by brewcore** [comment]
@Indyresjoel acknowledged.
1) It'd be good to address this outside the dev team as well - we need to solidify the ways we use Jira, do time tracking, etc; at least in the context of large projects.
3) Is there someplace that we've defined the skillset we're looking to hire? Other than input to 2)

**Comment by zachfedor** [comment]
I've already discussed this point with @Indyresjoel and @alexindrez, but I thought I'd post it here for everyone's benefit. [The Tuckman Stages](https://en.wikipedia.org/wiki/Tuckman%27s_stages_of_group_development) of group dynamics is a pretty well-received model for how a group forms and grows. They are necessary and inevitable. Since our last hiring spree, we are still a relatively young group according to this model. We have just started to dip our toes into stage 2, Storming. More hires will restart the entire process. That's also inevitable. But doing so before we mature through more of these stages will just compound the issues we face as a group, not just the technical issues the dev team faces with coding standards.

Poor organizational health is a much larger problem than poor code quality, in my opinion.

Further Reading:
- [The Advantage](https://www.amazon.com/Advantage-Enhanced-Organizational-Everything-Business-ebook/dp/B006ORWT3Y/#nav-subnav) by Patrick Lencioni
- [TL;DR](http://www.forbes.com/sites/danschawbel/2012/03/26/why-organizational-health-trumps-everything-else-in-business/#1e74f03408a6)

**Comment by Indyresjoel** [comment]
My favorite line of my jibberish is.....

> It seems inevitable.... .....that hiring is inevitable.

facepalm

**Comment by Indyresjoel** [comment]
@brewcore 

> 1) It'd be good to address this outside the dev team as well - we need to solidify the ways we use Jira, do time tracking, etc; at least in the context of large projects.
> 3) Is there someplace that we've defined the skillset we're looking to hire? Other than input to 2)

1) Agree with your assessment. This should be put to the IO committee for review.
3) Negative. There is the currently this https://wiki.theindustrialresolution.net:8091/display/INDREZ/Roles+and+Responsibilities but it doesn't highlight anything in particular. I'm quite open to input on peoples assessments of what would be great in new team members.

**Comment by manelius** [comment]
So for now we are operating under the assumption that we will be hiring 2 devs sooner rather than later, correct @Indyresjoel?
