### ISSUE TITLE
Committees, Comrades, Committees....

### ISSUE THREAD

**Issue by Indyresjoel** [Indyresjoel/theindyreshole#2]
In light of our recent retreat, the concept of moving forward and implementing change on the variety of issues that came up will be handled by Committees.  The reason for this approach is stemming from the fact that our company has reached a size and scale where it is becoming too difficult for any one person to stay effectively engaged in all the things that need to be done. This practice will help reinforce that we are a weakest link software team, not dependent upon rockstars to handle everything on their own. It will also empower the members of our team to take ownership of things that need to be addressed who are normally left out of conversations. 

To view issues documented, see https://wiki.theindustrialresolution.net:8091/pages/viewpage.action?spaceKey=INDREZ&title=2016+Stay-treat+Notes

Committee's will be comprised of 2-5 person groups of internal volunteers who will be granted 6 hours  per month to organize the issues to focus on dealing with, discuss and establish the priorities, propose solutions and a plan of implementation, and finally, communicate those plans with the rest of the team. 

Committee's are free to break up their time across the month however they would like. (three 2 hour meetings, six 1 hour meetings, two 2 hours meetings and 2 hours per person for individual research or "homework" assignments, etc). However, until approved, no more normal billable hours will be granted. The initial goal is to create steady, low velocity, organic growth/progress towards these important goals. Committee recommendations will always report back for approval from the Grand Central Committee (GCC - not the compiler*)

Committee's will be free to self assign, however, team members are not obligated to join a committee, and no team member should be on more than one committee unless special permission is granted or it is deemed necessary by the grand central committee of indy res (comprised of Joel, and his three additional personalities.). Each committee will have a committee chair and a reporter. The role of the chair is to facilitate, coordinate, and lead the group. The role of the reporter is to take minutes of the committee meetings and publish them on the company wiki for all team members to see. Report out, presentation, and a release will happen a minimum of once during each iteration. A committee iteration will last three months. A term of a committee member will be three months, and members will be expected to set achievable goals which can be tackled in a three month iteration. At the end of those three months, we will ask one person from each committee to step down so that another team member can step in, and also ask the chair to step down and let the group nominate a new chair. The chair is permitted to both step down and leave the group, satisfying both of the above requirements in one swoop.

Committee Voting will be employed whenever there is not a unanimous consensus on any official recommendation, endorsement, policy change, submission, etc.  Any official anything really. In the event of a vote, the decision will go to simple majority. 51% is all that is required to move in a direction. In the case of a split vote, caused either by an absent voter (committee person not present or able to vote), or an abstention vote (committee member doesn't want to vote for some reason)*, or also, if a committee is comprised of an even number of people, then those committee's finding themselves split in a simple majority voting scenario will pull in a member of the GCC to play the role of swing vote. If a member of GCC is unavailable, than a group of three people, drawn at random (from a hat style) from employee's present in the office the day of the vote can be selected to listen and weigh in with their vote.

*(in the event that someone decides to abstain, it should be done live so that their abstention vote can be recorded. Once abstained, that committee member cannot re-enter the vote and loses their right to weigh in on that issue. )

Once the GCC approves any motion or official action, the committee is then responsible to distribute and implement the changes. This includes trainings, updating company policies, etc. Any motion that passes through GCC will be wrote into policy. Policies will remain in place until an update to that policy is submitted to that policy by the appropriate committee and the GCC approves the update. So basically, if it passes, and you abstained, then you probably are gonna have to wait a while before an appeal is made, so be sure of yourself lol. 

The first initial wave of self assigning to committee's will be handled during a company wide meeting, during which time, the company will discuss and understand the committee's available, and hash out who is going to do what all at one time. 

The desired outcome of this committee creation and assignment is to provide steady, reassuring growth towards issues that are important to us as a company, and also to facilitate a means to encourage individual team members to trust in their comrades in handling things that are of interest to them so that they may feel at ease in letting go of things that would otherwise stress them out if it seemed as though no one was handling that shit. 

The initial committee's to be formed which are approved are: 
- The Committee of Community Betterment. Goal: Organize, grow, and coordinate outward community facing initiatives of our company. This committee could focus their attention on any of the following topics; the outward focus of company culture, diversity initiatives, volunteerism, activism, Pubforge community building, etc. In other words, this committee distributes and coordinates the ways in which our company manages that good ether which overflows from our cup on a regular basis. 
  Committee Members: @Mel-IndyRes, jonathan, Lauren
- The IO (Internal Operations) Committee. This company looks for ways to enhance the way we do what we do. Looking inward at what we have, they are focused on refinement of our current business models. Specifically, they are **NOT** to focus on envisioning new business models and direction for the company. As other committee's bring in new directions, this committee would then fold that new practice or model into their baby, which is the company process. They own operational process. This committee could focus their attention on any of the following topics; company communication, best practice enhancement, new resource and asset research, procedural/tactical policy writing, feature based iteration on any company digital assets (non marketing related). This committee will also weigh in and make suggestions on methodology and project management workflow improvements.
  Committee Members: @brewcore mike @zachfedor  Jake
- The Committee for Cultural Legacy. This committee maintains our culture, enhances it, and shares it with the world. This committee could focus their attention on any of the following topics; employee onboarding and exit, client on boarding and exit, company manual creation and enhancement (think graphic novel), culture focused marketing efforts to represent the company to the outside world, organizing internal team based events and outings, documenting and storytelling of the Indy Res office chronicles. 
  Committee Members: chris, jenny, jim.
- The Committee of Check Cutters. This committee is the purchasing department. They will receive requests for purchases from the entire team and organize those asks in priority for presentation to the GCC, who will then disburse funds to be used at the CCC's discretion. All purchases will flow through the process this committee creates and oversee's. They will also work to plot fixed expenses (ie: annual license renewals) for cash flow projection improvement and make requests of an annual budgetary earmarks for the various departments reflected in our P&L line items. In the third and fourth quarter of each year, this committee will aid the GCC in assembling and creating the annual budget. Of note; this committee will have to interact with Vicki. 
  Committee Members: @Mel-IndyRes alex, joel, sam
- The GCC. This is Joel. It's based on what Joel does naturally. It basically includes everything that he currently does, which is not handled by the above committees, or the individual team member roles as already established. Over time, this will be flushed out and documented better, so that we can look for opportunity to slice more off of this committee's shoulders, but for now, if we can do the above, that'd be fucking huge comrades. 

Okay. That's all for now. Cheers.

**Comment by Mel-IndyRes** [comment]
I really like this idea! GET SHIT DOOOONE

**Comment by brewcore** [comment]
Love the direction!  Only thought to add is the IO committee's mission seems a bit bigger than the others.

**Comment by zachfedor** [comment]
+1

also, i second what @brewcore said about the IO committee. it will be hard to come up with a measurable, attainable goal with such a large scope.

**Comment by Indyresjoel** [comment]
IO would likely be a larger committee and I would see it sectioning off chunks of things and splitting their individual attention onto different categories. For example, the committee decides that it wants to see improvement from the start in two specific and different areas; internal communication procedures and security focused best practices. They identify these are distinctly separate and split themselves into two sub-committees to each tackle one. Those groups report back in during normal committee meetings, each making a case for attention and resources and policy changes to be submitted for approval and distribution to the company accordingly, and as a group, they make decisions based off of which path seems to be most valuable to the company as a whole. 

Additionally, and I will make an edit above in the initial issue, committees that are even numbers and facing a majority voting scenario will be able to pull in a member of the GCC to play the role of swing vote. If a member of GCC is unavailable, than a group of three people, drawn at random (from a hat style) from employee's present in the office the day of the vote can be selected to listen and weigh in with their vote.

**Comment by zachfedor** [comment]
oh okay. that works for me!

**Comment by brewcore** [comment]
@Indyresjoel Should we allocate time this sprint to the initial meeting?

**Comment by brewcore** [comment]
I'm excited to get these finalized and moving.

**Comment by Indyresjoel** [comment]
All, please see the edited comment above to see committee assignments. Congratulations, you're all part of the initial charter of a brand new committee aimed at gettin shit done here at ye olde Indyres.

**Comment by sam** [comment]
(Wrong @sam.)
