### ISSUE TITLE
2016 Summer Writing Assignments: Part One - A day in the life of your future, future and future self.

### ISSUE THREAD

**Issue by Indyresjoel** [Indyresjoel/theindyreshole#4]
1) A day in the life... 
- This will be 3 individual assignments, each written as a creative short story which describes your daily routine on a normal work day in 2018, 2021, and 2026. 
- The intended use of this is to communicate our individual expectations and desires to the extent at which our minds are able to project the designs we have for our individual futures. A story has the power to ignite the imagination, and I would like to hear yours so that the we, as a company, can extract specific and tangible goals to work towards for you personally over the next ten years. 
- Once submitted and reviewed, we will then spend some time during our annual review session discussing the picture you painted and work collaboratively to identify those goals and make a note of them. The company will then compile all the individual goals and specifics and turn the meta information over to an HR committee for a plan to be set in place to start to work towards to goals of the masses. 
- Specific goals of an individual that the company can help work towards will be addressed between Joel and the employee individually. 
- Feel free to be as specific or as vague as you would like with people, places, and things. For instance, instead of saying "I drive to work at Industrial Resolution" you are welcome to say, "I drive to work at my awesome place of employment."  The idea is that no one can predict the future, and indeed, we are not trying to. Instead, we are simply painting a picture of where our expectations and desires meet one day in each of our futures. 
- No rules on length or word count. Just write until you're satisfied that you've communicated what a good day in the future looks like to you. Feel free to ask for peer review and critiques as you're writing as well! I'd be happy to help. 
- Due date: Thursday August 11th.

If you happen to hate creative writing assignments, call it something else. I believe that creativity takes many forms. Feel free to present or express yourself however you'd like. However, there is logic behind sticking more to storytelling and less to bullet points. The reason for communicating the future goals you have in a story form is that telling a story creates self-regulating interdependencies in order to finish the story. Painting the picture of a day in the life of your future self will assume lots of other things are in place, things that may not be worth a bullet to you on a list of goals, but still important for the company to hear about. Additionally, bullets often can be idealistic and able to be a strong statement that are inconsiderate of the needs of another bullet. A story built to weave them all together forces us to be understanding and realistic with our expectations. So that's why a creative assignment. If you'd like to outline the objectives or goals in addition to, or if you would like to create them as an outline to build your story around, you can present those with your story if you would like. If you flat out see no value or enjoyment out of doing this exercise, you can just tell me that and skip it entirely as well.

**Comment by alexindrez** [comment]
What is the deadline for this completed?

**Comment by Indyresjoel** [comment]
Whoops! Added. Thursday the 11th.

**Comment by manelius** [comment]
@Indyresjoel I'll be on vacation the 11th. Should I complete them before I leave, or will I have a couple extra days when I get back?

**Comment by Indyresjoel** [comment]
@manelius I want to read them and ponder them by the beach when I am on vacation. It's the only "work" thing that I'll be doing on vacation, and I'm okay with it because it is actually fun for me. If you can just try to have it to me by the 11th, I'd appreciate it. If not, I'll make time for it after.

**Comment by Mel-IndyRes** [comment]
@Indyresjoel  is this purely a homework assignment, or should we allot some time during work hours to tackle this? If the latter, how much time at most? An hour - hour and a half?

**Comment by manelius** [comment]
Good questions @Mel-IndyRes
